{{- if .Values.workers.monitor.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "name" . }}-monitor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        tier: aux
        run: celery-monitor
    spec:
      containers:
      - name: celery-monitor
        image: {{ .Values.api.app.image.repository}}:{{ .Values.api.app.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: 8888
            name: celery-monitor
        command:
          - "/usr/local/bin/celery"
          - "-A"
          - "async_worker"
          - "flower"
          - "--port=8888"
          - "--broker=redis://:{{ .Values.redis.redisPassword }}@{{ .Release.Name }}-{{ .Values.redis.nameOverride }}:6379/0"
      imagePullSecrets:
      - name: {{ .Values.api.pullSecret }}
{{- end }}
